USE top_songs;

CREATE TABLE Top5000 (
id INT NOT NULL,
artist VARCHAR(100) NULL,
song VARCHAR(100) NULL,
year INT NULL,
total DECIMAL (10,4) NULL,
usa DECIMAL (10,4) NULL,
uk DECIMAL (10,4) NULL,
eur DECIMAL (10,4) NULL,
rest DECIMAL (10,4) NULL,
PRIMARY KEY (id)
);

SELECT * FROM Top5000;